replicaCount: 3

image:
  repository: dein-dockerhub-benutzername/sample-app
  pullPolicy: Always
  tag: "v2"

service:
  type: LoadBalancer
  port: 80

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
